//the interface
keyboard.buildTextInterface = function(parent){
utils.makeHTML([{
			nav:{
				class:"navbar navbar-default navbar-static-top",
				role:"navigation",
				children:[
				{
					div:{
						class:"container-fluid",
						children:[
						{
							ul:{
								class:"nav navbar-nav navbar-left",
								children:[
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												onclick:keyboard.interface.onTextShrinked,
												children:[
												{
													span:{
														class:"glyphicon glyphicon-chevron-down"
													}
												}],
											}
										}]
									}
								},
								{	
									li:{
										children:[
										{
											a:{
												href:"#",
												onclick:keyboard.interface.onTextEnlarged,
												children:[
												{
													span:{
														class:"glyphicon glyphicon-chevron-up"
													}
												}],
											}
										}]
									}
								},
								{	
									li:{
										class:"dropdown",
										children:[
										{
											a:{
												href:"#",
												onclick:keyboard.interface.expandInterface,
												class:"dropdown-toggle",
												"data-toggle":"dropdown",
												children:[
												{
													table:{
														children:[
														{
															tr:{
																children:[
																{
																	td:{
																		children:[
																		{
																			div:{
																				id:"current_color",
																				class:"color_preview",
																			}
																		}]
																	}
																},{
																	td:{
																		children:[
																		{
																			span:{
																				class:"caret",
																			}
																		}]
																	}
																}]
															}
														}],
													}
												}]
											}
										},
										{
											ul:{ 
												id:"dropdown_menu_color",
												onclick:keyboard.interface.collapseInterface,
												class:"dropdown-menu",
												role:"menu",
												children:[{
													table:{
														id:"color_palette",
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										id:"boldCtl",
										children:[{
											a:{
												href:"#",
												onclick:keyboard.interface.onToggleBold,
												children:[{
													span:{
														class:"glyphicon glyphicon-bold"
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										id:"italicCtl",
										children:[{
											a:{
												href:"#",
												onclick:keyboard.interface.onToggleItalic,
												children:[{
													span:{
														class:"glyphicon glyphicon-italic"
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										class:"dropdown",
										children:[{
											a:{
												href:"#",
												onclick:keyboard.interface.expandInterface,
												class:"dropdown-toggle",
												"data-toggle":"dropdown",
												children:[{
													span:{
														id:"current_alignment",
														class:"glyphicon glyphicon-align-left",
													}
												},
												{
													span:{
														class:"caret"
													}
												}]
											}
										},
										{
											ul:{
												id:"dropdown_menu_align",
												onclick:keyboard.interface.collapseInterface,
												class:"dropdown-menu dropdown-menu-right",
												role:"menu",
												children:[
												{
													center:{
														children:[
														{
															table:{
																children:[
																{
																	tr:{
																		children:[
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignLeft,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-left",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		},
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignCenter,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-center",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		},
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignRight,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-right",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		},
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignJustified,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-justify",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		}]
																	}
																}]
															}
														}]
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												children:[{
													span:{
														class:"glyphicon glyphicon-list"	
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												children:[{
													span:{
														class:"glyphicon glyphicon-indent-left"	
													}
												}]
											}
										}]
									}
								},
								{	
									li:{
										children:[
										{
											a:{
												href:"#",
												children:[{
													span:{
														class:"glyphicon glyphicon-indent-right"	
													}
												}]
											}
										}]
									}
								}]
							}
						}],
					}
					
				}],
			}
		}],parent);
}