//the interface
keyboard.buildTextInterface = function(parent){
parent.innerHTML = '<div class="textinterfC"> <select id="_InterfT_font" class="textinterfT"> <option value="font">Font</option> </select> </div> <div id="_InterfT_-" class="textinterfC"> <span class="textinterfT">a</span> </div> <div id="_InterfT_+" class="textinterfC"> <span class="textinterfT">A</span> </div> <div id="_InterfT_color" class="textinterfC"> <li class="dropdown textinterfT"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <table> <tr> <td><div id="current_color" class="color_preview"></div></td> <td><span class="caret"></td> </tr> </table> </a> <ul id="dropdown_menu_color" class="dropdown-menu" role="menu"> <table id="color_palette"></table> </ul> </li> </div> <div id="_InterfT_bold" class="textinterfC"> <span class="textinterfT bold">B</span> </div> <div id="_InterfT_italic" class="textinterfC"> <span class="textinterfT italic">I</span> </div> <div id="_InterfT_align" class="textinterfC"> <li class="dropdown textinterfT"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span id="current_alignment" class="glyphicon glyphicon-align-left"></span> </a> <span class="caret"></span> <ul id="dropdown_menu_align" class="dropdown-menu dropdown-menu-right" role="menu"> <center> <table> <tr> <td class="dropdown_cell"> <li> <a id="_InterfT_alignLeft" href="#"> <span class="glyphicon glyphicon-align-left"></span> </a> </li> </td> <td class="dropdown_cell"> <li> <a id="_InterfT_alignCenter" href="#"> <span class="glyphicon glyphicon-align-center"></span> </a> </li> </td> <td class="dropdown_cell"> <li> <a id="_InterfT_alignRight" href="#"> <span class="glyphicon glyphicon-align-right"></span> </a> </li> </td> <td class="dropdown_cell"> <li> <a id="_InterfT_alignJustify" href="#"> <span class="glyphicon glyphicon-align-justify"></span> </a> </li> </td> </tr> </table> </center> </ul> </li> </div>';
/*
utils.makeHTML([{
			nav:{
				class:"navbar navbar-static-top",
				role:"navigation",
				children:[
				{
					div:{
						class:"container-fluid",
						children:[
						{
							ul:{
								class:"nav navbar-nav navbar-left",
								children:[
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												onclick:keyboard.interface.onTextShrinked,
												children:[
												{
													span:{
														class:"glyphicon glyphicon-chevron-down"
													}
												}],
											}
										}]
									}
								},
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												onclick:keyboard.interface.onTextEnlarged,
												children:[
												{
													span:{
														class:"glyphicon glyphicon-chevron-up"
													}
												}],
											}
										}]
									}
								},
								{
									li:{
										class:"dropdown",
										children:[
										{
											a:{
												href:"#",
												onclick:keyboard.interface.expandInterface,
												class:"dropdown-toggle",
												"data-toggle":"dropdown",
												children:[
												{
													table:{
														children:[
														{
															tr:{
																children:[
																{
																	td:{
																		children:[
																		{
																			div:{
																				id:"current_color",
																				class:"color_preview",
																			}
																		}]
																	}
																},{
																	td:{
																		children:[
																		{
																			span:{
																				class:"caret",
																			}
																		}]
																	}
																}]
															}
														}],
													}
												}]
											}
										},
										{
											ul:{
												id:"dropdown_menu_color",
												onclick:keyboard.interface.collapseInterface,
												class:"dropdown-menu",
												role:"menu",
												children:[{
													table:{
														id:"color_palette",
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										id:"boldCtl",
										children:[{
											a:{
												href:"#",
												onclick:keyboard.interface.onToggleBold,
												children:[{
													span:{
														class:"glyphicon glyphicon-bold"
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										id:"italicCtl",
										children:[{
											a:{
												href:"#",
												onclick:keyboard.interface.onToggleItalic,
												children:[{
													span:{
														class:"glyphicon glyphicon-italic"
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										class:"dropdown",
										children:[{
											a:{
												href:"#",
												onclick:keyboard.interface.expandInterface,
												class:"dropdown-toggle",
												"data-toggle":"dropdown",
												children:[{
													span:{
														id:"current_alignment",
														class:"glyphicon glyphicon-align-left",
													}
												},
												{
													span:{
														class:"caret"
													}
												}]
											}
										},
										{
											ul:{
												id:"dropdown_menu_align",
												onclick:keyboard.interface.collapseInterface,
												class:"dropdown-menu dropdown-menu-right",
												role:"menu",
												children:[
												{
													center:{
														children:[
														{
															table:{
																children:[
																{
																	tr:{
																		children:[
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignLeft,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-left",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		},
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignCenter,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-center",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		},
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignRight,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-right",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		},
																		{
																			td:{
																				class:"dropdown_cell",
																				children:[
																				{
																					li:{
																						children:[{
																							a:{
																								href:"#",
																								onclick:keyboard.interface.alignJustified,
																								children:[{
																									span:{
																										class:"glyphicon glyphicon-align-justify",
																									}
																								}]
																							}
																						}]
																					}
																				}]
																			}
																		}]
																	}
																}]
															}
														}]
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												children:[{
													span:{
														class:"glyphicon glyphicon-list"
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												children:[{
													span:{
														class:"glyphicon glyphicon-indent-left"
													}
												}]
											}
										}]
									}
								},
								{
									li:{
										children:[
										{
											a:{
												href:"#",
												children:[{
													span:{
														class:"glyphicon glyphicon-indent-right"
													}
												}]
											}
										}]
									}
								}]
							}
						}],
					}

				}],
			}
		}],parent);
		*/
}
